# Generated by Django 2.0.4 on 2018-04-03 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='text',
        ),
    ]
